name: adrian.pw

dependencies:
  - astropy
  - numpy
  - cython
  - matplotlib
  - scipy
  - jupyter
  - notebook
  - ipython
  - pip:
    - pelican
    - fabric
    - Markdown
    - git+https://github.com/jakevdp/JSAnimation.git
    - ads
    - ghp-import
